
const swaggerJsDoc = require('swagger-jsdoc');
const swaggerUI = require('swagger-ui-express');

const swaggerOptions = {
    swaggerDefinition: {
        info: {
            title: 'Node Swagger API',
            description: 'Test API with autogenerated swagger doc',
            version: '1.0.0',
        }
    },
    apis: ['./src/server.js'],
};
const swaggerDocs = swaggerJsDoc(swaggerOptions);

module.exports = {
    swaggerSetup: swaggerUI.setup(swaggerDocs),
    swaggerServe: swaggerUI.serve,
};